-- Generated by scripts/supabase/database/generate-database-sql.mjs
-- Creates relational tables that mirror the current data/*.ts files.

create table if not exists public.users (
  id text not null,
  first_name text not null,
  last_name text not null,
  display_name text not null,
  initials text not null,
  joined_on date not null,
  role text not null check (role in ('member', 'admin')),
  email text not null,
  primary key (id),
  unique (email)
);

create table if not exists public.league_clubs (
  name text not null,
  slug text not null,
  badge_path text not null,
  badge_source_url text not null,
  primary key (slug),
  unique (name)
);

create table if not exists public.matchday_game_weeks (
  primary key (id)
);

create table if not exists public.market_analysis_snapshots (
  primary key (id)
);

create table if not exists public.market_analysis_selections (
  primary key (id)
);

create table if not exists public.matchday_proposals (
  primary key (id),
  unique (game_week_id, proposal_id)
);

create table if not exists public.matchday_bet_lines (
  primary key (id)
);

create table if not exists public.matchday_forms (
  primary key (id)
);

create table if not exists public.matchday_form_matches (
  primary key (id)
);

create table if not exists public.league_data_meta (
  id text not null,
  simulated_at_iso timestamptz not null,
  updated_at_iso timestamptz not null,
  primary key (id)
);

create table if not exists public.league_data_matchday_simulations (
  primary key (id),
  unique (game_week_id)
);

create table if not exists public.league_data_votes (
  primary key (id),
  unique (simulation_id, user_id)
);

create table if not exists public.league_data_bet_line_odds (
  primary key (id)
);

create table if not exists public.league_data_slips (
  primary key (id)
);

create table if not exists public.league_data_leg_results (
  primary key (id)
);

create table if not exists public.ledger_data (
  primary key (id)
);

create table if not exists public.matchday_seed (
  primary key (id)
);

grant usage on schema public to authenticated;

grant select on public.users to authenticated;
drop policy if exists "Authenticated users can read users" on public.users;
create policy "Authenticated users can read users"
on public.users
for select
to authenticated
using (true);

grant select on public.league_clubs to authenticated;
drop policy if exists "Authenticated users can read league_clubs" on public.league_clubs;
create policy "Authenticated users can read league_clubs"
on public.league_clubs
for select
to authenticated
using (true);

grant select on public.matchday_game_weeks to authenticated;
drop policy if exists "Authenticated users can read matchday_game_weeks" on public.matchday_game_weeks;
create policy "Authenticated users can read matchday_game_weeks"
on public.matchday_game_weeks
for select
to authenticated
using (true);

grant select on public.market_analysis_snapshots to authenticated;
drop policy if exists "Authenticated users can read market_analysis_snapshots" on public.market_analysis_snapshots;
create policy "Authenticated users can read market_analysis_snapshots"
on public.market_analysis_snapshots
for select
to authenticated
using (true);

grant select on public.market_analysis_selections to authenticated;
drop policy if exists "Authenticated users can read market_analysis_selections" on public.market_analysis_selections;
create policy "Authenticated users can read market_analysis_selections"
on public.market_analysis_selections
for select
to authenticated
using (true);

grant select on public.matchday_proposals to authenticated;
drop policy if exists "Authenticated users can read matchday_proposals" on public.matchday_proposals;
create policy "Authenticated users can read matchday_proposals"
on public.matchday_proposals
for select
to authenticated
using (true);

grant select on public.matchday_bet_lines to authenticated;
drop policy if exists "Authenticated users can read matchday_bet_lines" on public.matchday_bet_lines;
create policy "Authenticated users can read matchday_bet_lines"
on public.matchday_bet_lines
for select
to authenticated
using (true);

grant select on public.matchday_forms to authenticated;
drop policy if exists "Authenticated users can read matchday_forms" on public.matchday_forms;
create policy "Authenticated users can read matchday_forms"
on public.matchday_forms
for select
to authenticated
using (true);

grant select on public.matchday_form_matches to authenticated;
drop policy if exists "Authenticated users can read matchday_form_matches" on public.matchday_form_matches;
create policy "Authenticated users can read matchday_form_matches"
on public.matchday_form_matches
for select
to authenticated
using (true);

grant select on public.league_data_meta to authenticated;
drop policy if exists "Authenticated users can read league_data_meta" on public.league_data_meta;
create policy "Authenticated users can read league_data_meta"
on public.league_data_meta
for select
to authenticated
using (true);

grant select on public.league_data_matchday_simulations to authenticated;
drop policy if exists "Authenticated users can read league_data_matchday_simulations" on public.league_data_matchday_simulations;
create policy "Authenticated users can read league_data_matchday_simulations"
on public.league_data_matchday_simulations
for select
to authenticated
using (true);

grant select on public.league_data_votes to authenticated;
drop policy if exists "Authenticated users can read league_data_votes" on public.league_data_votes;
create policy "Authenticated users can read league_data_votes"
on public.league_data_votes
for select
to authenticated
using (true);

grant select on public.league_data_bet_line_odds to authenticated;
drop policy if exists "Authenticated users can read league_data_bet_line_odds" on public.league_data_bet_line_odds;
create policy "Authenticated users can read league_data_bet_line_odds"
on public.league_data_bet_line_odds
for select
to authenticated
using (true);

grant select on public.league_data_slips to authenticated;
drop policy if exists "Authenticated users can read league_data_slips" on public.league_data_slips;
create policy "Authenticated users can read league_data_slips"
on public.league_data_slips
for select
to authenticated
using (true);

grant select on public.league_data_leg_results to authenticated;
drop policy if exists "Authenticated users can read league_data_leg_results" on public.league_data_leg_results;
create policy "Authenticated users can read league_data_leg_results"
on public.league_data_leg_results
for select
to authenticated
using (true);

grant select on public.ledger_data to authenticated;
drop policy if exists "Authenticated users can read ledger_data" on public.ledger_data;
create policy "Authenticated users can read ledger_data"
on public.ledger_data
for select
to authenticated
using (true);

grant select on public.matchday_seed to authenticated;
drop policy if exists "Authenticated users can read matchday_seed" on public.matchday_seed;
create policy "Authenticated users can read matchday_seed"
on public.matchday_seed
for select
to authenticated
using (true);
