-- Generated by scripts/supabase/database/generate-database-sql.mjs
-- Seeds the relational tables from the current data/*.ts files.

insert into public.users (id, first_name, last_name, display_name, initials, joined_on, role, email)
values
  ('brian-scott', 'Brian', 'Scott', 'Brian Scott', 'BS', '2026-03-23', 'admin', 'brianscott1980@gmail.com'),
  ('tony-mclean', 'Tony', 'McLean', 'Tony McLean', 'TM', '2026-03-23', 'member', 'tonymclean@live.co.uk'),
  ('john-colreavey', 'John', 'Colreavey', 'John Colreavey', 'JC', '2026-03-23', 'member', 'jcolreavey@gmail.com'),
  ('paul-melville', 'Paul', 'Melville', 'Paul Melville', 'PM', '2026-03-23', 'member', 'p.melville@hotmail.co.uk'),
  ('alasdair-head', 'Alasdair', 'Head', 'Alasdair Head', 'AH', '2026-03-23', 'member', 'alasdairhead@hotmail.co.uk'),
  ('paul-devine', 'Paul', 'Devine', 'Paul Devine', 'PD', '2026-03-23', 'member', 'pauldevine54@msn.com'),
  ('derek-mcmillan', 'Derek', 'McMillan', 'Derek McMillan', 'DM', '2026-03-23', 'member', 'derek.mcmillan81@gmail.com')
on conflict (id) do nothing;

insert into public.league_clubs (name, slug, badge_path, badge_source_url)
values
  ('Arsenal', 'arsenal', '/assets/clubs/premier-league/arsenal.png', 'https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png'),
  ('Aston Villa', 'aston-villa', '/assets/clubs/premier-league/aston-villa.png', 'https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png'),
  ('Bournemouth', 'bournemouth', '/assets/clubs/premier-league/bournemouth.png', 'https://r2.thesportsdb.com/images/media/team/badge/y08nak1534071116.png'),
  ('Brentford', 'brentford', '/assets/clubs/premier-league/brentford.png', 'https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png'),
  ('Brighton & Hove Albion', 'brighton-hove-albion', '/assets/clubs/premier-league/brighton-hove-albion.png', 'https://r2.thesportsdb.com/images/media/team/badge/ywypts1448810904.png'),
  ('Burnley', 'burnley', '/assets/clubs/premier-league/burnley.png', 'https://r2.thesportsdb.com/images/media/team/badge/ql7nl31686893820.png'),
  ('Chelsea', 'chelsea', '/assets/clubs/premier-league/chelsea.png', 'https://r2.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png'),
  ('Crystal Palace', 'crystal-palace', '/assets/clubs/premier-league/crystal-palace.png', 'https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png'),
  ('Everton', 'everton', '/assets/clubs/premier-league/everton.png', 'https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png'),
  ('Fulham', 'fulham', '/assets/clubs/premier-league/fulham.png', 'https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png'),
  ('Leeds United', 'leeds-united', '/assets/clubs/premier-league/leeds-united.png', 'https://r2.thesportsdb.com/images/media/team/badge/jcgrml1756649030.png'),
  ('Liverpool', 'liverpool', '/assets/clubs/premier-league/liverpool.png', 'https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png'),
  ('Manchester City', 'manchester-city', '/assets/clubs/premier-league/manchester-city.png', 'https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png'),
  ('Manchester United', 'manchester-united', '/assets/clubs/premier-league/manchester-united.png', 'https://r2.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png'),
  ('Newcastle United', 'newcastle-united', '/assets/clubs/premier-league/newcastle-united.png', 'https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png'),
  ('Nottingham Forest', 'nottingham-forest', '/assets/clubs/premier-league/nottingham-forest.png', 'https://r2.thesportsdb.com/images/media/team/badge/bk4qjs1546440351.png'),
  ('Sunderland', 'sunderland', '/assets/clubs/premier-league/sunderland.png', 'https://r2.thesportsdb.com/images/media/team/badge/tprtus1448813498.png'),
  ('Tottenham Hotspur', 'tottenham-hotspur', '/assets/clubs/premier-league/tottenham-hotspur.png', 'https://r2.thesportsdb.com/images/media/team/badge/dfyfhl1604094109.png'),
  ('West Ham United', 'west-ham-united', '/assets/clubs/premier-league/west-ham-united.png', 'https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png'),
  ('Wolverhampton Wanderers', 'wolverhampton-wanderers', '/assets/clubs/premier-league/wolverhampton-wanderers.png', 'https://r2.thesportsdb.com/images/media/team/badge/u9qr031621593327.png')
on conflict (slug) do nothing;

insert into public.matchday_game_weeks ()
values

on conflict (id) do nothing;

insert into public.market_analysis_snapshots ()
values

on conflict (id) do nothing;

insert into public.market_analysis_selections ()
values

on conflict (id) do nothing;

insert into public.matchday_proposals ()
values

on conflict (id) do nothing;

insert into public.matchday_bet_lines ()
values

on conflict (id) do nothing;

insert into public.matchday_forms ()
values

on conflict (id) do nothing;

insert into public.matchday_form_matches ()
values

on conflict (id) do nothing;

insert into public.league_data_meta (id, simulated_at_iso, updated_at_iso)
values
  ('primary', '2026-04-03T08:59:10.218Z', '2026-04-03T08:59:10.218Z')
on conflict (id) do nothing;

insert into public.league_data_matchday_simulations ()
values

on conflict (id) do nothing;

insert into public.league_data_votes ()
values

on conflict (id) do nothing;

insert into public.league_data_bet_line_odds ()
values

on conflict (id) do nothing;

insert into public.league_data_slips ()
values

on conflict (id) do nothing;

insert into public.league_data_leg_results ()
values

on conflict (id) do nothing;

insert into public.ledger_data ()
values

on conflict (id) do nothing;

insert into public.matchday_seed ()
values

on conflict (id) do nothing;
