-- Generated by scripts/supabase/database/generate-database-sql.mjs
-- Creates relational tables that mirror the current data/*.ts files.

create table if not exists public.users (
  id text not null,
  first_name text,
  last_name text,
  display_name text,
  initials text,
  joined_on date,
  role text check (role in ('member', 'admin')),
  email text,
  primary key (id),
  unique (email)
);

alter table public.users enable row level security;

create table if not exists public.league_clubs (
  name text,
  slug text not null,
  badge_path text,
  badge_source_url text,
  primary key (slug),
  unique (name)
);

alter table public.league_clubs enable row level security;

create table if not exists public.matchday_game_weeks (
  id text not null,
  slug text,
  name text,
  description text,
  window_start_iso timestamptz,
  window_end_iso timestamptz,
  starts_in text,
  proposal_ids jsonb,
  votes_by_user_id jsonb,
  simulated_slip jsonb,
  primary key (id)
);

alter table public.matchday_game_weeks enable row level security;

create table if not exists public.market_analysis_snapshots (
  id text not null,
  bookmaker text check (bookmaker in ('Ladbrokes')),
  snapshot_date date,
  matchday_id text,
  primary key (id),
  foreign key (matchday_id) references public.matchday_game_weeks (id)
);

alter table public.market_analysis_snapshots enable row level security;

create table if not exists public.market_analysis_selections (
  id text not null,
  snapshot_id text,
  fixture text,
  market text,
  selection text,
  decimal_odds numeric(10, 2),
  primary key (id),
  foreign key (snapshot_id) references public.market_analysis_snapshots (id)
);

alter table public.market_analysis_selections enable row level security;

create table if not exists public.matchday_proposals (
  id text not null,
  game_week_id text,
  proposal_id text,
  risk_level text check (risk_level in ('safe', 'balanced', 'aggressive')),
  title text,
  summary text,
  legs integer,
  status_label text,
  cashout_watch_list jsonb,
  bet_line_ids jsonb,
  ai_recommended boolean,
  primary key (id),
  unique (game_week_id, proposal_id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.matchday_proposals enable row level security;

create table if not exists public.matchday_bet_lines (
  id text not null,
  game_week_id text,
  proposal_entity_id text,
  sort_order integer,
  label text,
  schedule_note text,
  ai_reasoning text,
  form_id text,
  form_note text,
  market_id text,
  odds text,
  primary key (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id),
  foreign key (proposal_entity_id) references public.matchday_proposals (id),
  foreign key (market_id) references public.market_analysis_selections (id)
);

alter table public.matchday_bet_lines enable row level security;

create table if not exists public.matchday_forms (
  id text not null,
  game_week_id text,
  proposal_id text,
  bet_line_id text,
  primary key (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id),
  foreign key (bet_line_id) references public.matchday_bet_lines (id)
);

alter table public.matchday_forms enable row level security;

create table if not exists public.matchday_form_matches (
  id text not null,
  form_id text,
  team_side text check (team_side in ('home', 'away')),
  sort_order integer,
  opponent text,
  venue text check (venue in ('H', 'A')),
  final_score text,
  goals_scored integer,
  outcome text check (outcome in ('W', 'D', 'L')),
  primary key (id),
  foreign key (form_id) references public.matchday_forms (id)
);

alter table public.matchday_form_matches enable row level security;

create table if not exists public.custom_bets (
  id text not null,
  slug text,
  title text,
  state text check (state in ('pending', 'staked')),
  custom_bet_type text check (custom_bet_type in ('standard', 'free_bet_offer')),
  sport text check (sport in ('horse_racing', 'football', 'golf')),
  bookmaker text check (bookmaker in ('Ladbrokes')),
  event_name text,
  competition_name text,
  betting_format_requested text,
  proposed_bets jsonb,
  recommended_market text,
  recommended_selection text,
  decimal_odds numeric(10, 2),
  summary text,
  analysis_summary text,
  media_summary text,
  timeline_title text,
  timeline_description text,
  generated_at_iso timestamptz,
  event_start_iso timestamptz,
  event_end_iso timestamptz,
  suggested_stake_amount numeric(12, 2),
  is_free_stake boolean,
  placed_proposal_rank integer check (placed_proposal_rank in (1, 2, 3)),
  placed_market text,
  placed_selection text,
  stake_amount numeric(12, 2),
  placed_decimal_odds numeric(10, 2),
  placed_at_iso timestamptz,
  outcome_status text check (outcome_status in ('won', 'lost', 'cashed_out')),
  outcome_value_amount numeric(12, 2),
  outcome_at_iso timestamptz,
  outcome_summary text,
  outcome_submitted_by text,
  cashout_lower_target text,
  cashout_upper_target text,
  no_cashout_value text,
  cashout_advice jsonb,
  watch_points jsonb,
  risk_factors jsonb,
  horse_racing jsonb,
  football jsonb,
  golf jsonb,
  primary key (id),
  unique (slug)
);

alter table public.custom_bets enable row level security;

create table if not exists public.league_data_meta (
  id text not null,
  simulated_at_iso timestamptz,
  updated_at_iso timestamptz,
  primary key (id)
);

alter table public.league_data_meta enable row level security;

create table if not exists public.league_data_matchday_simulations (
  id text not null,
  game_week_id text,
  vote_resolved_at_iso timestamptz,
  bet_placed_at_iso timestamptz,
  selected_proposal_id text,
  slip_id text,
  primary key (id),
  unique (game_week_id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.league_data_matchday_simulations enable row level security;

create table if not exists public.league_data_votes (
  id text not null,
  simulation_id text,
  game_week_id text,
  user_id text,
  proposal_id text,
  primary key (id),
  unique (simulation_id, user_id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id),
  foreign key (user_id) references public.users (id)
);

alter table public.league_data_votes enable row level security;

create table if not exists public.league_data_bet_line_odds (
  id text not null,
  simulation_id text,
  game_week_id text,
  sort_order integer,
  bet_line_label text,
  odds numeric(10, 2),
  primary key (id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.league_data_bet_line_odds enable row level security;

create table if not exists public.league_data_slips (
  id text not null,
  simulation_id text,
  game_week_id text,
  proposal_id text,
  timeline_label text,
  stake numeric(12, 2),
  is_free_stake boolean,
  placed_decimal_odds numeric(10, 2),
  stake_placed_at timestamptz,
  settled_at timestamptz,
  settlement_kind text check (settlement_kind in ('settled', 'cashout')),
  return_amount numeric(12, 2),
  status text check (status in ('win', 'loss')),
  primary key (id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.league_data_slips enable row level security;

create table if not exists public.league_data_leg_results (
  id text not null,
  simulation_id text,
  slip_id text,
  game_week_id text,
  sort_order integer,
  bet_line_label text,
  kickoff_at timestamptz,
  settled_at timestamptz,
  final_score text,
  status text check (status in ('won', 'lost', 'cashed_out')),
  actual_status text check (actual_status in ('won', 'lost')),
  primary key (id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (slip_id) references public.league_data_slips (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.league_data_leg_results enable row level security;

create table if not exists public.ledger_data (
  id text not null,
  title text,
  date_iso timestamptz,
  amount numeric(12, 2),
  kind text check (kind in ('deposit', 'stake', 'settlement')),
  game_week_id text,
  proposal_id text,
  primary key (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.ledger_data enable row level security;

create table if not exists public.timeline_events (
  id text not null,
  title text,
  description text,
  timestamp_iso timestamptz,
  kind text check (kind in ('matchday_proposal_generated')),
  matchday_id text,
  primary key (id),
  foreign key (matchday_id) references public.matchday_game_weeks (id)
);

alter table public.timeline_events enable row level security;

create table if not exists public.matchday_outcomes (
  id text not null,
  game_week_id text,
  proposal_id text,
  outcome_status text check (outcome_status in ('won', 'lost', 'cashed_out')),
  outcome_value_amount numeric(12, 2),
  outcome_at_iso timestamptz,
  summary text,
  submitted_by text,
  primary key (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

alter table public.matchday_outcomes enable row level security;

create table if not exists public.custom_bet_outcomes (
  id text not null,
  custom_bet_id text,
  outcome_status text check (outcome_status in ('won', 'lost', 'cashed_out')),
  outcome_value_amount numeric(12, 2),
  outcome_at_iso timestamptz,
  summary text,
  submitted_by text,
  primary key (id),
  foreign key (custom_bet_id) references public.custom_bets (id)
);

alter table public.custom_bet_outcomes enable row level security;

create table if not exists public.matchday_seed (
  id text not null,
  slug text,
  name text,
  description text,
  window_start_iso timestamptz,
  window_end_iso timestamptz,
  starts_in text,
  proposals jsonb,
  votes_by_user_id jsonb,
  simulated_slip jsonb,
  primary key (id)
);

alter table public.matchday_seed enable row level security;

grant usage on schema public to authenticated;

grant select on public.users to authenticated;
drop policy if exists "Authenticated users can read users" on public.users;
create policy "Authenticated users can read users"
on public.users
for select
to authenticated
using (true);

grant select on public.league_clubs to authenticated;
drop policy if exists "Authenticated users can read league_clubs" on public.league_clubs;
create policy "Authenticated users can read league_clubs"
on public.league_clubs
for select
to authenticated
using (true);

grant select on public.matchday_game_weeks to authenticated;
drop policy if exists "Authenticated users can read matchday_game_weeks" on public.matchday_game_weeks;
create policy "Authenticated users can read matchday_game_weeks"
on public.matchday_game_weeks
for select
to authenticated
using (true);

grant insert, update on public.matchday_game_weeks to authenticated;
drop policy if exists "Authenticated admins can insert matchday_game_weeks" on public.matchday_game_weeks;
create policy "Authenticated admins can insert matchday_game_weeks"
on public.matchday_game_weeks
for insert
to authenticated
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Authenticated admins can update matchday_game_weeks" on public.matchday_game_weeks;
create policy "Authenticated admins can update matchday_game_weeks"
on public.matchday_game_weeks
for update
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.market_analysis_snapshots to authenticated;
drop policy if exists "Authenticated users can read market_analysis_snapshots" on public.market_analysis_snapshots;
create policy "Authenticated users can read market_analysis_snapshots"
on public.market_analysis_snapshots
for select
to authenticated
using (true);

grant select on public.market_analysis_selections to authenticated;
drop policy if exists "Authenticated users can read market_analysis_selections" on public.market_analysis_selections;
create policy "Authenticated users can read market_analysis_selections"
on public.market_analysis_selections
for select
to authenticated
using (true);

grant select on public.matchday_proposals to authenticated;
drop policy if exists "Authenticated users can read matchday_proposals" on public.matchday_proposals;
create policy "Authenticated users can read matchday_proposals"
on public.matchday_proposals
for select
to authenticated
using (true);

grant select on public.matchday_bet_lines to authenticated;
drop policy if exists "Authenticated users can read matchday_bet_lines" on public.matchday_bet_lines;
create policy "Authenticated users can read matchday_bet_lines"
on public.matchday_bet_lines
for select
to authenticated
using (true);

grant select on public.matchday_forms to authenticated;
drop policy if exists "Authenticated users can read matchday_forms" on public.matchday_forms;
create policy "Authenticated users can read matchday_forms"
on public.matchday_forms
for select
to authenticated
using (true);

grant select on public.matchday_form_matches to authenticated;
drop policy if exists "Authenticated users can read matchday_form_matches" on public.matchday_form_matches;
create policy "Authenticated users can read matchday_form_matches"
on public.matchday_form_matches
for select
to authenticated
using (true);

grant select on public.custom_bets to authenticated;
drop policy if exists "Authenticated users can read custom_bets" on public.custom_bets;
create policy "Authenticated users can read custom_bets"
on public.custom_bets
for select
to authenticated
using (true);

grant insert, update on public.custom_bets to authenticated;
drop policy if exists "Authenticated admins can insert custom_bets" on public.custom_bets;
create policy "Authenticated admins can insert custom_bets"
on public.custom_bets
for insert
to authenticated
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Authenticated admins can update custom_bets" on public.custom_bets;
create policy "Authenticated admins can update custom_bets"
on public.custom_bets
for update
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.league_data_meta to authenticated;
drop policy if exists "Authenticated users can read league_data_meta" on public.league_data_meta;
create policy "Authenticated users can read league_data_meta"
on public.league_data_meta
for select
to authenticated
using (true);

grant insert, update on public.league_data_meta to authenticated;
drop policy if exists "Authenticated admins can insert league_data_meta" on public.league_data_meta;
create policy "Authenticated admins can insert league_data_meta"
on public.league_data_meta
for insert
to authenticated
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Authenticated admins can update league_data_meta" on public.league_data_meta;
create policy "Authenticated admins can update league_data_meta"
on public.league_data_meta
for update
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.league_data_matchday_simulations to authenticated;
drop policy if exists "Authenticated users can read league_data_matchday_simulations" on public.league_data_matchday_simulations;
create policy "Authenticated users can read league_data_matchday_simulations"
on public.league_data_matchday_simulations
for select
to authenticated
using (true);

grant insert, update on public.league_data_matchday_simulations to authenticated;
drop policy if exists "Authenticated admins can insert league_data_matchday_simulations" on public.league_data_matchday_simulations;
create policy "Authenticated admins can insert league_data_matchday_simulations"
on public.league_data_matchday_simulations
for insert
to authenticated
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Authenticated admins can update league_data_matchday_simulations" on public.league_data_matchday_simulations;
create policy "Authenticated admins can update league_data_matchday_simulations"
on public.league_data_matchday_simulations
for update
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.league_data_votes to authenticated;
drop policy if exists "Authenticated users can read league_data_votes" on public.league_data_votes;
create policy "Authenticated users can read league_data_votes"
on public.league_data_votes
for select
to authenticated
using (true);

grant insert, update on public.league_data_votes to authenticated;
drop policy if exists "Authenticated admins can insert league_data_votes" on public.league_data_votes;
create policy "Authenticated admins can insert league_data_votes"
on public.league_data_votes
for insert
to authenticated
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Authenticated admins can update league_data_votes" on public.league_data_votes;
create policy "Authenticated admins can update league_data_votes"
on public.league_data_votes
for update
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.league_data_bet_line_odds to authenticated;
drop policy if exists "Authenticated users can read league_data_bet_line_odds" on public.league_data_bet_line_odds;
create policy "Authenticated users can read league_data_bet_line_odds"
on public.league_data_bet_line_odds
for select
to authenticated
using (true);

grant select on public.league_data_slips to authenticated;
drop policy if exists "Authenticated users can read league_data_slips" on public.league_data_slips;
create policy "Authenticated users can read league_data_slips"
on public.league_data_slips
for select
to authenticated
using (true);

grant insert, update on public.league_data_slips to authenticated;
drop policy if exists "Authenticated admins can insert league_data_slips" on public.league_data_slips;
create policy "Authenticated admins can insert league_data_slips"
on public.league_data_slips
for insert
to authenticated
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Authenticated admins can update league_data_slips" on public.league_data_slips;
create policy "Authenticated admins can update league_data_slips"
on public.league_data_slips
for update
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.league_data_leg_results to authenticated;
drop policy if exists "Authenticated users can read league_data_leg_results" on public.league_data_leg_results;
create policy "Authenticated users can read league_data_leg_results"
on public.league_data_leg_results
for select
to authenticated
using (true);

grant select on public.ledger_data to authenticated;
drop policy if exists "Authenticated users can read ledger_data" on public.ledger_data;
create policy "Authenticated users can read ledger_data"
on public.ledger_data
for select
to authenticated
using (true);

grant select on public.timeline_events to authenticated;
drop policy if exists "Authenticated users can read timeline_events" on public.timeline_events;
create policy "Authenticated users can read timeline_events"
on public.timeline_events
for select
to authenticated
using (true);

grant select on public.matchday_outcomes to authenticated;
drop policy if exists "Authenticated users can read matchday_outcomes" on public.matchday_outcomes;
create policy "Authenticated users can read matchday_outcomes"
on public.matchday_outcomes
for select
to authenticated
using (true);

grant insert, update on public.matchday_outcomes to authenticated;
drop policy if exists "Authenticated admins can write matchday_outcomes" on public.matchday_outcomes;
create policy "Authenticated admins can write matchday_outcomes"
on public.matchday_outcomes
for all
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.custom_bet_outcomes to authenticated;
drop policy if exists "Authenticated users can read custom_bet_outcomes" on public.custom_bet_outcomes;
create policy "Authenticated users can read custom_bet_outcomes"
on public.custom_bet_outcomes
for select
to authenticated
using (true);

grant insert, update on public.custom_bet_outcomes to authenticated;
drop policy if exists "Authenticated admins can write custom_bet_outcomes" on public.custom_bet_outcomes;
create policy "Authenticated admins can write custom_bet_outcomes"
on public.custom_bet_outcomes
for all
to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

grant select on public.matchday_seed to authenticated;
drop policy if exists "Authenticated users can read matchday_seed" on public.matchday_seed;
create policy "Authenticated users can read matchday_seed"
on public.matchday_seed
for select
to authenticated
using (true);

create or replace function public.fetch_app_data_snapshot()
returns jsonb
language sql
stable
security invoker
as $$
  select jsonb_build_object(
    'users',
    coalesce((select jsonb_agg(to_jsonb(users_row)) from public.users as users_row), '[]'::jsonb),
    'leagueClubs',
    coalesce(
      (select jsonb_agg(to_jsonb(clubs_row)) from public.league_clubs as clubs_row),
      '[]'::jsonb
    ),
    'marketAnalysisSnapshotRows',
    coalesce(
      (
        select jsonb_agg(to_jsonb(snapshots_row))
        from public.market_analysis_snapshots as snapshots_row
      ),
      '[]'::jsonb
    ),
    'marketAnalysisSelectionRows',
    coalesce(
      (
        select jsonb_agg(to_jsonb(selections_row))
        from public.market_analysis_selections as selections_row
      ),
      '[]'::jsonb
    ),
    'matchdayGameWeeks',
    coalesce(
      (
        select jsonb_agg(to_jsonb(matchday_weeks_row))
        from public.matchday_game_weeks as matchday_weeks_row
      ),
      '[]'::jsonb
    ),
    'matchdayProposals',
    coalesce(
      (
        select jsonb_agg(to_jsonb(proposals_row))
        from public.matchday_proposals as proposals_row
      ),
      '[]'::jsonb
    ),
    'matchdayBetLines',
    coalesce(
      (
        select jsonb_agg(to_jsonb(bet_lines_row))
        from public.matchday_bet_lines as bet_lines_row
      ),
      '[]'::jsonb
    ),
    'matchdayForms',
    coalesce(
      (
        select jsonb_agg(to_jsonb(forms_row))
        from public.matchday_forms as forms_row
      ),
      '[]'::jsonb
    ),
    'matchdayFormMatches',
    coalesce(
      (
        select jsonb_agg(to_jsonb(form_matches_row))
        from public.matchday_form_matches as form_matches_row
      ),
      '[]'::jsonb
    ),
    'customBets',
    coalesce(
      (
        select jsonb_agg(to_jsonb(custom_bets_row))
        from public.custom_bets as custom_bets_row
      ),
      '[]'::jsonb
    ),
    'leagueDataMeta',
    coalesce(
      (
        select jsonb_agg(to_jsonb(league_meta_row))
        from public.league_data_meta as league_meta_row
      ),
      '[]'::jsonb
    ),
    'leagueDataMatchdaySimulations',
    coalesce(
      (
        select jsonb_agg(to_jsonb(simulations_row))
        from public.league_data_matchday_simulations as simulations_row
      ),
      '[]'::jsonb
    ),
    'leagueDataVotes',
    coalesce(
      (
        select jsonb_agg(to_jsonb(votes_row))
        from public.league_data_votes as votes_row
      ),
      '[]'::jsonb
    ),
    'leagueDataBetLineOdds',
    coalesce(
      (
        select jsonb_agg(to_jsonb(odds_row))
        from public.league_data_bet_line_odds as odds_row
      ),
      '[]'::jsonb
    ),
    'leagueDataSlips',
    coalesce(
      (
        select jsonb_agg(to_jsonb(slips_row))
        from public.league_data_slips as slips_row
      ),
      '[]'::jsonb
    ),
    'leagueDataLegResults',
    coalesce(
      (
        select jsonb_agg(to_jsonb(leg_results_row))
        from public.league_data_leg_results as leg_results_row
      ),
      '[]'::jsonb
    ),
    'ledgerData',
    coalesce(
      (select jsonb_agg(to_jsonb(ledger_row)) from public.ledger_data as ledger_row),
      '[]'::jsonb
    ),
    'timelineEvents',
    coalesce(
      (
        select jsonb_agg(to_jsonb(timeline_events_row))
        from public.timeline_events as timeline_events_row
      ),
      '[]'::jsonb
    ),
    'matchdayOutcomes',
    coalesce(
      (
        select jsonb_agg(to_jsonb(matchday_outcomes_row))
        from public.matchday_outcomes as matchday_outcomes_row
      ),
      '[]'::jsonb
    ),
    'customBetOutcomes',
    coalesce(
      (
        select jsonb_agg(to_jsonb(custom_bet_outcomes_row))
        from public.custom_bet_outcomes as custom_bet_outcomes_row
      ),
      '[]'::jsonb
    ),
    'betLearningFeedback',
    '[]'::jsonb
  );
$$;

grant execute on function public.fetch_app_data_snapshot() to authenticated;
