-- Generated by scripts/supabase/database/generate-database-sql.mjs
-- Creates relational tables that mirror the current data/*.ts files.

create table if not exists public.users (
  id text not null,
  first_name text not null,
  last_name text not null,
  display_name text not null,
  initials text not null,
  joined_on date not null,
  role text not null check (role in ('member', 'admin')),
  email text not null,
  primary key (id),
  unique (email)
);

create table if not exists public.league_clubs (
  name text not null,
  slug text not null,
  badge_path text not null,
  badge_source_url text not null,
  primary key (slug),
  unique (name)
);

create table if not exists public.matchday_game_weeks (
  id text not null,
  slug text not null,
  name text not null,
  description text not null,
  window_start_iso timestamptz not null,
  window_end_iso timestamptz not null,
  starts_in text not null,
  proposal_ids jsonb not null,
  votes_by_user_id jsonb not null,
  simulated_slip jsonb,
  primary key (id)
);

create table if not exists public.market_analysis_snapshots (
  id text not null,
  bookmaker text not null check (bookmaker in ('Ladbrokes')),
  snapshot_date date not null,
  matchday_id text not null,
  primary key (id),
  foreign key (matchday_id) references public.matchday_game_weeks (id)
);

create table if not exists public.market_analysis_selections (
  id text not null,
  snapshot_id text not null,
  fixture text not null,
  market text not null,
  selection text not null,
  decimal_odds numeric(10, 2) not null,
  primary key (id),
  foreign key (snapshot_id) references public.market_analysis_snapshots (id)
);

create table if not exists public.matchday_proposals (
  id text not null,
  game_week_id text not null,
  proposal_id text not null,
  risk_level text not null check (risk_level in ('safe', 'balanced', 'aggressive')),
  title text not null,
  summary text not null,
  legs integer not null,
  status_label text not null,
  bet_line_ids jsonb not null,
  ai_recommended boolean,
  primary key (id),
  unique (game_week_id, proposal_id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

create table if not exists public.matchday_bet_lines (
  id text not null,
  game_week_id text not null,
  proposal_entity_id text not null,
  sort_order integer not null,
  label text not null,
  schedule_note text not null,
  ai_reasoning text not null,
  form_id text,
  form_note text,
  market_id text,
  odds text,
  primary key (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id),
  foreign key (proposal_entity_id) references public.matchday_proposals (id),
  foreign key (market_id) references public.market_analysis_selections (id)
);

create table if not exists public.matchday_forms (
  id text not null,
  game_week_id text not null,
  proposal_id text not null,
  bet_line_id text not null,
  primary key (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id),
  foreign key (bet_line_id) references public.matchday_bet_lines (id)
);

create table if not exists public.matchday_form_matches (
  id text not null,
  form_id text not null,
  team_side text not null check (team_side in ('home', 'away')),
  sort_order integer not null,
  opponent text not null,
  venue text not null check (venue in ('H', 'A')),
  final_score text not null,
  goals_scored integer not null,
  outcome text not null check (outcome in ('W', 'D', 'L')),
  primary key (id),
  foreign key (form_id) references public.matchday_forms (id)
);

create table if not exists public.league_data_meta (
  id text not null,
  simulated_at_iso timestamptz not null,
  updated_at_iso timestamptz not null,
  primary key (id)
);

create table if not exists public.league_data_matchday_simulations (
  id text not null,
  game_week_id text not null,
  vote_resolved_at_iso timestamptz not null,
  bet_placed_at_iso timestamptz not null,
  selected_proposal_id text not null,
  slip_id text not null,
  primary key (id),
  unique (game_week_id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

create table if not exists public.league_data_votes (
  id text not null,
  simulation_id text not null,
  game_week_id text not null,
  user_id text not null,
  proposal_id text not null,
  primary key (id),
  unique (simulation_id, user_id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id),
  foreign key (user_id) references public.users (id)
);

create table if not exists public.league_data_bet_line_odds (
  id text not null,
  simulation_id text not null,
  game_week_id text not null,
  sort_order integer not null,
  bet_line_label text not null,
  odds numeric(10, 2) not null,
  primary key (id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

create table if not exists public.league_data_slips (
  id text not null,
  simulation_id text not null,
  game_week_id text not null,
  proposal_id text not null,
  timeline_label text not null,
  stake numeric(12, 2) not null,
  stake_placed_at timestamptz not null,
  settled_at timestamptz not null,
  settlement_kind text not null check (settlement_kind in ('settled', 'cashout')),
  return_amount numeric(12, 2) not null,
  status text not null check (status in ('win', 'loss')),
  primary key (id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

create table if not exists public.league_data_leg_results (
  id text not null,
  simulation_id text not null,
  slip_id text not null,
  game_week_id text not null,
  sort_order integer not null,
  bet_line_label text not null,
  kickoff_at timestamptz not null,
  settled_at timestamptz not null,
  final_score text not null,
  status text not null check (status in ('won', 'lost', 'cashed_out')),
  actual_status text not null check (actual_status in ('won', 'lost')),
  primary key (id),
  foreign key (simulation_id) references public.league_data_matchday_simulations (id),
  foreign key (slip_id) references public.league_data_slips (id),
  foreign key (game_week_id) references public.matchday_game_weeks (id)
);

create table if not exists public.ledger_data (
  id text not null,
  title text not null,
  date_iso timestamptz not null,
  amount numeric(12, 2) not null,
  kind text not null check (kind in ('deposit', 'stake', 'settlement')),
  primary key (id)
);

create table if not exists public.matchday_seed (
  id text not null,
  slug text not null,
  name text not null,
  description text not null,
  window_start_iso timestamptz not null,
  window_end_iso timestamptz not null,
  starts_in text not null,
  proposals jsonb not null,
  votes_by_user_id jsonb not null,
  simulated_slip jsonb,
  primary key (id)
);
