import type { MatchdayBetLineRecord } from "../types/matchday_type";

export const matchdayBetLines = [
  {
    "id": "betline-md-1-aggressive-inter-roma-btts",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-aggressive",
    "sortOrder": 4,
    "label": "Inter Milan v Roma: Both teams to score",
    "scheduleNote": "Sun 5 Apr, 18:45 BST",
    "aiReasoning": "Roma have scored in four of their last five league matches and Inter's defensive line has looked less secure recently. With Lautaro expected back and Roma still carrying enough attacking quality, the BTTS leg gives the Sunday finish a stronger upside swing.",
    "formId": "form-md-1-inter-roma",
    "formNote": "Inter have scored 6 and Roma 11 across their last five Serie A matches.",
    "marketId": "market-md-1-inter-roma-btts-yes",
    "odds": "1.91"
  },
  {
    "id": "betline-md-1-aggressive-leverkusen-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-aggressive",
    "sortOrder": 1,
    "label": "Bayer Leverkusen v Wolfsburg: Bayer Leverkusen to win",
    "scheduleNote": "Sat 4 Apr, 13:30 BST",
    "aiReasoning": "Leverkusen still profile as the stronger side on form and urgency, and Wolfsburg's defensive run makes them hard to trust away from home. This stays in as the first aggressive anchor before the higher-variance legs kick in.",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "formNote": "Last five league goals: Bayer Leverkusen 9, Wolfsburg 6.",
    "marketId": "market-md-1-leverkusen-win",
    "odds": "1.40"
  },
  {
    "id": "betline-md-1-aggressive-mallorca-real-btts",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-aggressive",
    "sortOrder": 2,
    "label": "Mallorca v Real Madrid: Both teams to score",
    "scheduleNote": "Sat 4 Apr, 15:15 BST",
    "aiReasoning": "Madrid have scored in every one of their last five league games but have also conceded in four of those five. Mallorca are light on wins, yet their home setup still forces them to trade chances, which keeps the BTTS price live enough for the higher-risk slip.",
    "formId": "form-md-1-mallorca-real",
    "formNote": "Mallorca have scored 3 and Real Madrid 11 across their last five La Liga matches.",
    "marketId": "market-md-1-mallorca-real-btts-yes",
    "odds": "1.67"
  },
  {
    "id": "betline-md-1-aggressive-real-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-aggressive",
    "sortOrder": 3,
    "label": "Mallorca v Real Madrid: Real Madrid to win",
    "scheduleNote": "Sat 4 Apr, 15:15 BST",
    "aiReasoning": "Keeping Madrid on the slip lets the aggressive build still lean on the stronger team even while pairing it with a goals angle. Mallorca's recent downturn and Madrid's top-end attacking floor keep the away result in play.",
    "formId": "form-md-1-mallorca-real",
    "formNote": "Last five league goals: Mallorca 3, Real Madrid 11.",
    "marketId": "market-md-1-real-win",
    "odds": "1.65"
  },
  {
    "id": "betline-md-1-balanced-bayern-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-balanced",
    "sortOrder": 1,
    "label": "SC Freiburg v Bayern Munich: Bayern Munich to win",
    "scheduleNote": "Sat 4 Apr, 13:30 BST",
    "aiReasoning": "Bayern's last five league matches have produced five wins and 18 goals, and Freiburg have still been vulnerable against top-six attacking quality. The price is short, but it gives the balanced slip an early anchor without overcomplicating the first leg.",
    "formId": "form-md-1-freiburg-bayern",
    "formNote": "Last five league goals: Freiburg 6, Bayern Munich 18.",
    "marketId": "market-md-1-bayern-win",
    "odds": "1.40"
  },
  {
    "id": "betline-md-1-balanced-inter-roma-btts",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-balanced",
    "sortOrder": 3,
    "label": "Inter Milan v Roma: Both teams to score",
    "scheduleNote": "Sun 5 Apr, 18:45 BST",
    "aiReasoning": "Inter have kept only one clean sheet across their last five Serie A matches, while Roma have scored 11 goals over their last five league games. Lautaro's return strengthens the home attack enough to back both sides finding one.",
    "formId": "form-md-1-inter-roma",
    "formNote": "Inter have scored 6 and Roma 11 across their last five Serie A matches.",
    "marketId": "market-md-1-inter-roma-btts-yes",
    "odds": "1.91"
  },
  {
    "id": "betline-md-1-balanced-real-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-balanced",
    "sortOrder": 2,
    "label": "Mallorca v Real Madrid: Real Madrid to win",
    "scheduleNote": "Sat 4 Apr, 15:15 BST",
    "aiReasoning": "Mallorca have taken only two points from their last five league games and scored just three times in that run. Madrid do carry rotation risk with a European tie ahead, but their shot volume and recent away output still make the straight win the calmer angle here.",
    "formId": "form-md-1-mallorca-real",
    "formNote": "Last five league goals: Mallorca 3, Real Madrid 11.",
    "marketId": "market-md-1-real-win",
    "odds": "1.65"
  },
  {
    "id": "betline-md-1-safe-bayern-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-safe",
    "sortOrder": 1,
    "label": "SC Freiburg v Bayern Munich: Bayern Munich to win",
    "scheduleNote": "Sat 4 Apr, 13:30 BST",
    "aiReasoning": "Bayern arrive on a five-game Bundesliga winning run with 18 goals scored, while Freiburg have taken only two wins from their last five league outings. Even with European fixtures nearby, the away-win line is still the cleanest low-volatility read.",
    "formId": "form-md-1-freiburg-bayern",
    "formNote": "Last five league goals: Freiburg 6, Bayern Munich 18.",
    "marketId": "market-md-1-bayern-win",
    "odds": "1.40"
  },
  {
    "id": "betline-md-1-safe-inter-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-safe",
    "sortOrder": 3,
    "label": "Inter Milan v Roma: Inter Milan to win",
    "scheduleNote": "Sun 5 Apr, 18:45 BST",
    "aiReasoning": "Inter get Lautaro Martinez back for Sunday and remain top of Serie A. Roma have scored well recently, but their selection noise makes the straight home win safer than pushing immediately into a higher-variance goals play.",
    "formId": "form-md-1-inter-roma",
    "formNote": "Last five league goals: Inter Milan 6, Roma 11.",
    "marketId": "market-md-1-inter-win",
    "odds": "1.67"
  },
  {
    "id": "betline-md-1-safe-leverkusen-win",
    "gameWeekId": "md-1",
    "proposalEntityId": "proposal-md-1-safe",
    "sortOrder": 2,
    "label": "Bayer Leverkusen v Wolfsburg: Bayer Leverkusen to win",
    "scheduleNote": "Sat 4 Apr, 13:30 BST",
    "aiReasoning": "Leverkusen still need a strong run for the European places and have lost only once in their last five league matches. Wolfsburg are winless in five league games and have shipped 13 goals across that spell.",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "formNote": "Last five league goals: Bayer Leverkusen 9, Wolfsburg 6.",
    "marketId": "market-md-1-leverkusen-win",
    "odds": "1.40"
  },
  {
    "id": "betline-md-2-aggressive-barcelona-win",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-aggressive",
    "sortOrder": 1,
    "label": "Barcelona v Atletico Madrid: Barcelona to win",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "Barcelona's 15 goals in their last five with a 4W-1D run gives this aggressive slip a controlled opener at 1.54, while Atletico's recent 3-loss profile adds away-side variance. If Barcelona stop creating box entries after taking the lead, protect before the higher-price legs.",
    "formId": "form-md-2-barcelona-atletico",
    "formNote": "Last five goals: Barcelona 15, Atletico Madrid 11.",
    "marketId": "market-md-2-barcelona-win",
    "odds": "1.54"
  },
  {
    "id": "betline-md-2-aggressive-braga-win",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-aggressive",
    "sortOrder": 4,
    "label": "Braga v Real Betis: Braga to win",
    "scheduleNote": "Thu 9 Apr, 17:45 BST",
    "aiReasoning": "Braga (8 goals in five) and Betis (6 in five) supports a live game with result volatility, and 2.60 gives the aggressive card its biggest late payout lever. If Betis dominate transition moments and territory early, this leg should be de-risked quickly.",
    "formId": "form-md-2-braga-betis",
    "formNote": "Recent goals in last five: Braga 8, Real Betis 6.",
    "marketId": "market-md-2-braga-win",
    "odds": "2.60"
  },
  {
    "id": "betline-md-2-aggressive-psg-liverpool-over-3-5",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-aggressive",
    "sortOrder": 3,
    "label": "Paris SG v Liverpool: Over 3.5 goals",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "PSG's 16 goals in five versus Liverpool's 6 still supports a high-event ceiling when game state opens early, which is why over 3.5 is used as the volatility leg at 2.20. If first-half tempo is slow with low shot volume, this angle weakens fast.",
    "formId": "form-md-2-psg-liverpool",
    "formNote": "Recent scoring profile: Paris SG 16 goals, Liverpool 6 goals across their last five matches.",
    "marketId": "market-md-2-psg-liverpool-over-3-5",
    "odds": "2.20"
  },
  {
    "id": "betline-md-2-aggressive-psg-win",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-aggressive",
    "sortOrder": 2,
    "label": "Paris SG v Liverpool: Paris SG to win",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "PSG to win at 1.75 is kept because their 16-goal recent output gives stronger attacking momentum than Liverpool's 6-goal run. It raises upside before the totals leg, but if PSG lose midfield control the risk profile changes immediately.",
    "formId": "form-md-2-psg-liverpool",
    "formNote": "Last five goals: Paris SG 16, Liverpool 6.",
    "marketId": "market-md-2-psg-win",
    "odds": "1.75"
  },
  {
    "id": "betline-md-2-balanced-barcelona-win",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-balanced",
    "sortOrder": 1,
    "label": "Barcelona v Atletico Madrid: Barcelona to win",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "Barcelona's 15 goals and 4W-1D recent run versus Atletico's three defeats in five makes 1.54 the best lower-variance opener for the balanced card. This leg's job is stability, so a flat Barcelona press or reduced chance quality is an early caution flag.",
    "formId": "form-md-2-barcelona-atletico",
    "formNote": "Last five goals: Barcelona 15, Atletico Madrid 11.",
    "marketId": "market-md-2-barcelona-win",
    "odds": "1.54"
  },
  {
    "id": "betline-md-2-balanced-braga-betis-over-2-5",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-balanced",
    "sortOrder": 3,
    "label": "Braga v Real Betis: Over 2.5 goals",
    "scheduleNote": "Thu 9 Apr, 17:45 BST",
    "aiReasoning": "Braga (8) and Betis (6) goals across the last five gives enough shared scoring evidence to support over 2.5 at 1.90 as a balanced enhancer. It improves payout without forcing a side call, but a slow first half with few box touches is a clear danger pattern.",
    "formId": "form-md-2-braga-betis",
    "formNote": "Last five goals: Braga 8, Real Betis 6.",
    "marketId": "market-md-2-braga-betis-over-2-5",
    "odds": "1.90"
  },
  {
    "id": "betline-md-2-balanced-psg-win",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-balanced",
    "sortOrder": 2,
    "label": "Paris SG v Liverpool: Paris SG to win",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "PSG's 16-goal recent trend versus Liverpool's 6 supports taking the straight win at 1.75 instead of DNB for better balanced-card return. If PSG cannot sustain field tilt and Liverpool start winning second balls in midfield, this edge narrows quickly.",
    "formId": "form-md-2-psg-liverpool",
    "formNote": "Last five goals: Paris SG 16, Liverpool 6.",
    "marketId": "market-md-2-psg-win",
    "odds": "1.75"
  },
  {
    "id": "betline-md-2-safe-barcelona-win",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-safe",
    "sortOrder": 1,
    "label": "Barcelona v Atletico Madrid: Barcelona to win",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "Barcelona's 4W-1D recent sequence with 15 goals against Atletico's three losses in five gives the safest opening result profile at 1.54. This leg is defensive-card control, so if Barcelona lose territorial control early the slip should be protected sooner.",
    "formId": "form-md-2-barcelona-atletico",
    "formNote": "Last five goals: Barcelona 15, Atletico Madrid 11.",
    "marketId": "market-md-2-barcelona-win",
    "odds": "1.54"
  },
  {
    "id": "betline-md-2-safe-betis-dnb",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-safe",
    "sortOrder": 3,
    "label": "Braga v Real Betis: Real Betis draw no bet",
    "scheduleNote": "Thu 9 Apr, 17:45 BST",
    "aiReasoning": "With Braga on 8 and Betis on 6 goals across recent form, this matchup has enough uncertainty that Betis draw-no-bet at 1.80 is preferred over a full-result exposure. The protection value disappears if Betis are pinned back for sustained spells.",
    "formId": "form-md-2-braga-betis",
    "formNote": "Recent goals in last five: Braga 8, Real Betis 6.",
    "marketId": "market-md-2-betis-dnb",
    "odds": "1.80"
  },
  {
    "id": "betline-md-2-safe-psg-dnb",
    "gameWeekId": "md-2",
    "proposalEntityId": "proposal-md-2-safe",
    "sortOrder": 2,
    "label": "Paris SG v Liverpool: Paris SG draw no bet",
    "scheduleNote": "Wed 8 Apr, 20:00 BST",
    "aiReasoning": "PSG's 16 goals and 4W-0D-1L recent profile versus Liverpool's 6-goal run supports a PSG-side position, but draw-no-bet at 1.36 is used to cap downside in the safe card. If PSG defensive shape looks stretched in transitions, this leg should be managed conservatively.",
    "formId": "form-md-2-psg-liverpool",
    "formNote": "Last five goals: Paris SG 16, Liverpool 6.",
    "marketId": "market-md-2-psg-dnb",
    "odds": "1.36"
  },
  {
    "id": "betline-md-3-aggressive-bournemouth-forest-over-2-5",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-aggressive",
    "sortOrder": 3,
    "label": "Bournemouth v Nottingham Forest: Over 2.5 goals",
    "scheduleNote": "Sat 18 Apr, 15:00 BST",
    "aiReasoning": "Bournemouth's home matches average 3.1 goals this season, and Forest have scored in 4 of their last 5 away. This high-variance goals play anchors the aggressive Saturday card. Invalidation: A cagey opening with <0.5 xG total by 30 mins.",
    "formId": "form-md-3-bournemouth-forest",
    "formNote": "Last five goals: Bournemouth 9, Forest 7. Over 2.5 landed in 3/5 for Bmth.",
    "marketId": "market-md-3-bournemouth-forest-over-2-5",
    "odds": "1.90"
  },
  {
    "id": "betline-md-3-aggressive-leeds-brentford-draw",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-aggressive",
    "sortOrder": 1,
    "label": "Leeds United v Brentford: Match to end in Draw",
    "scheduleNote": "Sat 18 Apr, 15:00 BST",
    "aiReasoning": "Two of the last 4 meetings ended in draws, and both sides have had 2 draws in their last 5 league games. A compact tactical battle at Elland Road supports the 3.40 price. If an early goal forces the game to open into a shootout, the draw is invalidated.",
    "formId": "form-md-3-leeds-brentford",
    "formNote": "Leeds last five: 1W-3D-1L. Brentford: 1W-2D-2L. Closely matched on xG benchmarks.",
    "marketId": "market-md-3-leeds-brentford-draw",
    "odds": "3.40"
  },
  {
    "id": "betline-md-3-aggressive-sunderland-win",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-aggressive",
    "sortOrder": 2,
    "label": "Sunderland v Burnley: Sunderland to win",
    "scheduleNote": "Mon 20 Apr, 20:00 BST",
    "aiReasoning": "Sunderland have won 3 our of their last 5 at the Stadium of Light, and Burnley has shown vulnerability against high-pressing sides like the Black Cats. The 2.85 price offers the best risk/reward in the aggressive card. If Burnley take an early lead and sit back, exit immediately.",
    "formId": "form-md-3-sunderland-burnley",
    "formNote": "Sunderland last five: 3W-0D-2L, 7 goals. Burnley: 2W-1D-2L, 6 goals.",
    "marketId": "market-md-3-sunderland-win",
    "odds": "2.85"
  },
  {
    "id": "betline-md-3-balanced-chelsea-brighton-over-2-5",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-balanced",
    "sortOrder": 1,
    "label": "Chelsea v Brighton & Hove Albion: Over 2.5 goals",
    "scheduleNote": "Sat 18 Apr, 17:30 BST",
    "aiReasoning": "Both sides have scored in 4 of their last 5 games, with a combined 23 goals produced in those fixtures. Brighton's high line and Chelsea's transition speed support over 2.5 at 1.65. A low-intensity first 20 minutes with <3 combined shots is a key exit trigger.",
    "formId": "form-md-3-chelsea-brighton",
    "formNote": "Chelsea goals (last 5): 10. Brighton: 13. High-event trends from both sides.",
    "marketId": "market-md-3-chelsea-brighton-over-2-5",
    "odds": "1.65"
  },
  {
    "id": "betline-md-3-balanced-spurs-villa-btts",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-balanced",
    "sortOrder": 2,
    "label": "Tottenham Hotspur v Aston Villa: Both teams to score",
    "scheduleNote": "Sun 19 Apr, 14:00 BST",
    "aiReasoning": "Spurs have kept zero clean sheets in 5 games, and Villa have scored in 9 of their last 10 away trips. The BTTS market at 1.55 accounts for both sides' attacking intent and defensive rotation. If either manager adopts a narrow 5-4-1 block, the BTTS value is lost.",
    "formId": "form-md-3-spurs-villa",
    "formNote": "Last five: Spurs 8 goals (0 CS), Villa 9 goals. BTTS landed in 4/5 for each.",
    "marketId": "market-md-3-spurs-villa-btts",
    "odds": "1.55"
  },
  {
    "id": "betline-md-3-balanced-united-newcastle-btts",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-balanced",
    "sortOrder": 3,
    "label": "Manchester United v Newcastle United: Both teams to score",
    "scheduleNote": "Sun 19 Apr, 16:30 BST",
    "aiReasoning": "United have scored in 5 straight home games, while Newcastle's away form shows 10 goals in their last five. Both sides thrive in transition play which suits a BTTS slip. Invalidation: A sudden defensive shift or a red card for a key attacker early in the game.",
    "formId": "form-md-3-united-newcastle",
    "formNote": "Man Utd goals (last 5): 9. Newcastle: 10. Defensive consistency is low for both side (2 CS combined).",
    "marketId": "market-md-3-united-newcastle-btts",
    "odds": "1.55"
  },
  {
    "id": "betline-md-3-safe-arsenal-win",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-safe",
    "sortOrder": 1,
    "label": "Arsenal v Fulham: Arsenal to win",
    "scheduleNote": "Sat 18 Apr, 15:00 BST",
    "aiReasoning": "Arsenal have won 4 of their last 5 league games, scoring 12 goals. Fulham's away defense has conceded in 5 consecutive matches, making the home win at 1.45 a high-probability anchor. If Arsenal's shot conversion is low in the first half, consider a partial cashout.",
    "formId": "form-md-3-arsenal-fulham",
    "formNote": "Last five goals: Arsenal 12, Fulham 5. Arsenal 4W-1L-0D.",
    "marketId": "market-md-3-arsenal-win",
    "odds": "1.45"
  },
  {
    "id": "betline-md-3-safe-liverpool-win",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-safe",
    "sortOrder": 3,
    "label": "Everton v Liverpool: Liverpool to win",
    "scheduleNote": "Sat 18 Apr, 12:30 BST",
    "aiReasoning": "Liverpool have won the last 3 derbies and enter on a 5-match unbeaten run with 11 goals scored. Everton's attacking injuries reduce their threat today. If Liverpool lose early control of transitions or concede from a set-piece, confidence in the away win will drop significantly.",
    "formId": "form-md-3-everton-liverpool",
    "formNote": "Liverpool last five: 4W-1D-0L, 11 goals. Everton: 1W-1D-3L, 4 goals.",
    "marketId": "market-md-3-liverpool-win",
    "odds": "1.68"
  },
  {
    "id": "betline-md-3-safe-mancity-westham-over-1-5",
    "gameWeekId": "md-3",
    "proposalEntityId": "proposal-md-3-safe",
    "sortOrder": 2,
    "label": "Manchester City v West Ham United: Over 1.5 goals",
    "scheduleNote": "Sat 18 Apr, 15:00 BST",
    "aiReasoning": "City's last 5 matches averaged 3.4 goals per game, and West Ham have seen over 1.5 in every one of their last 5 outings. This market adds stability to the safe slip. A tactical lockdown from West Ham with <2 City shots on target early would invalidate this.",
    "formId": "form-md-3-mancity-westham",
    "formNote": "City goals (last 5): 17. West Ham goals: 7. All five City games had 2+ goals.",
    "marketId": "market-md-3-mancity-westham-over-1-5",
    "odds": "1.22"
  }
] as unknown as MatchdayBetLineRecord[];
