import type { MatchdayFormMatchRecord } from "../types/matchday_type";

export const matchdayFormMatches = [
  {
    "id": "formmatch-md-1-bayern-1",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Borussia Monchengladbach",
    "venue": "H",
    "finalScore": "4-1",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-bayern-2",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Borussia Dortmund",
    "venue": "A",
    "finalScore": "2-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-bayern-3",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Eintracht Frankfurt",
    "venue": "H",
    "finalScore": "3-2",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-bayern-4",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Werder Bremen",
    "venue": "A",
    "finalScore": "0-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-bayern-5",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "TSG Hoffenheim",
    "venue": "H",
    "finalScore": "5-1",
    "goalsScored": 5,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-freiburg-1",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Bayer Leverkusen",
    "venue": "H",
    "finalScore": "3-3",
    "goalsScored": 3,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-freiburg-2",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Eintracht Frankfurt",
    "venue": "A",
    "finalScore": "2-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-freiburg-3",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Borussia Monchengladbach",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-freiburg-4",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "TSG Hoffenheim",
    "venue": "A",
    "finalScore": "3-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-freiburg-5",
    "formId": "form-md-1-freiburg-bayern",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Werder Bremen",
    "venue": "H",
    "finalScore": "1-0",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-inter-1",
    "formId": "form-md-1-inter-roma",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Fiorentina",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-inter-2",
    "formId": "form-md-1-inter-roma",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Atalanta",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-inter-3",
    "formId": "form-md-1-inter-roma",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "AC Milan",
    "venue": "A",
    "finalScore": "1-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-inter-4",
    "formId": "form-md-1-inter-roma",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Genoa",
    "venue": "H",
    "finalScore": "2-0",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-inter-5",
    "formId": "form-md-1-inter-roma",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Lecce",
    "venue": "A",
    "finalScore": "0-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-leverkusen-1",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "SC Freiburg",
    "venue": "A",
    "finalScore": "3-3",
    "goalsScored": 3,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-leverkusen-2",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Hamburger SV",
    "venue": "A",
    "finalScore": "0-1",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-leverkusen-3",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Mainz",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-leverkusen-4",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Union Berlin",
    "venue": "A",
    "finalScore": "1-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-leverkusen-5",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "St. Pauli",
    "venue": "H",
    "finalScore": "4-0",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-mallorca-1",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Osasuna",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-mallorca-2",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Real Sociedad",
    "venue": "H",
    "finalScore": "0-1",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-mallorca-3",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Celta Vigo",
    "venue": "A",
    "finalScore": "2-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-mallorca-4",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Real Betis",
    "venue": "H",
    "finalScore": "1-2",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-mallorca-5",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Barcelona",
    "venue": "A",
    "finalScore": "3-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-real-1",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Elche",
    "venue": "H",
    "finalScore": "4-1",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-real-2",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Celta Vigo",
    "venue": "A",
    "finalScore": "1-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-real-3",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Getafe",
    "venue": "H",
    "finalScore": "0-1",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-real-4",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Osasuna",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-real-5",
    "formId": "form-md-1-mallorca-real",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Real Sociedad",
    "venue": "H",
    "finalScore": "4-1",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-roma-1",
    "formId": "form-md-1-inter-roma",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Genoa",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-roma-2",
    "formId": "form-md-1-inter-roma",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Juventus",
    "venue": "H",
    "finalScore": "3-3",
    "goalsScored": 3,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-roma-3",
    "formId": "form-md-1-inter-roma",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Cremonese",
    "venue": "H",
    "finalScore": "3-0",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-roma-4",
    "formId": "form-md-1-inter-roma",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Napoli",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-roma-5",
    "formId": "form-md-1-inter-roma",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Cagliari",
    "venue": "H",
    "finalScore": "2-0",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-1-wolfsburg-1",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Hamburger SV",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-wolfsburg-2",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "VfB Stuttgart",
    "venue": "H",
    "finalScore": "0-4",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-wolfsburg-3",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "FC Augsburg",
    "venue": "A",
    "finalScore": "3-2",
    "goalsScored": 2,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-1-wolfsburg-4",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "RB Leipzig",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-1-wolfsburg-5",
    "formId": "form-md-1-leverkusen-wolfsburg",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Borussia Dortmund",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-atletico-1",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Barcelona",
    "venue": "H",
    "finalScore": "1-2",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-atletico-2",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Real Madrid",
    "venue": "A",
    "finalScore": "3-2",
    "goalsScored": 2,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-atletico-3",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Tottenham Hotspur",
    "venue": "A",
    "finalScore": "3-2",
    "goalsScored": 2,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-atletico-4",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Getafe",
    "venue": "H",
    "finalScore": "1-0",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-atletico-5",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Tottenham Hotspur",
    "venue": "H",
    "finalScore": "5-2",
    "goalsScored": 5,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-barcelona-1",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Rayo Vallecano",
    "venue": "H",
    "finalScore": "1-0",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-barcelona-2",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Newcastle United",
    "venue": "H",
    "finalScore": "7-2",
    "goalsScored": 7,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-barcelona-3",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Sevilla",
    "venue": "H",
    "finalScore": "5-2",
    "goalsScored": 5,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-barcelona-4",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Newcastle United",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-2-barcelona-5",
    "formId": "form-md-2-barcelona-atletico",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Athletic Club",
    "venue": "A",
    "finalScore": "0-1",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-betis-1",
    "formId": "form-md-2-braga-betis",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Athletic Club",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-betis-2",
    "formId": "form-md-2-braga-betis",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Panathinaikos",
    "venue": "H",
    "finalScore": "4-0",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-betis-3",
    "formId": "form-md-2-braga-betis",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Celta Vigo",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-2-betis-4",
    "formId": "form-md-2-braga-betis",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Panathinaikos",
    "venue": "A",
    "finalScore": "1-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-betis-5",
    "formId": "form-md-2-braga-betis",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Getafe",
    "venue": "A",
    "finalScore": "2-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-braga-1",
    "formId": "form-md-2-braga-betis",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Ferencvaros",
    "venue": "A",
    "finalScore": "2-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-braga-2",
    "formId": "form-md-2-braga-betis",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Sporting CP",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-2-braga-3",
    "formId": "form-md-2-braga-betis",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Nacional",
    "venue": "A",
    "finalScore": "1-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-braga-4",
    "formId": "form-md-2-braga-betis",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Vitoria Guimaraes",
    "venue": "H",
    "finalScore": "3-2",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-braga-5",
    "formId": "form-md-2-braga-betis",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Gil Vicente",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-liverpool-1",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Manchester City",
    "venue": "A",
    "finalScore": "4-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-liverpool-2",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Brighton & Hove Albion",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-liverpool-3",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Galatasaray",
    "venue": "H",
    "finalScore": "4-0",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-liverpool-4",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Tottenham Hotspur",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-2-liverpool-5",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Galatasaray",
    "venue": "A",
    "finalScore": "1-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-2-psg-1",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Toulouse",
    "venue": "H",
    "finalScore": "3-1",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-psg-2",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Nice",
    "venue": "A",
    "finalScore": "0-4",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-psg-3",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Chelsea",
    "venue": "A",
    "finalScore": "0-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-psg-4",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Chelsea",
    "venue": "H",
    "finalScore": "5-2",
    "goalsScored": 5,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-2-psg-5",
    "formId": "form-md-2-psg-liverpool",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Monaco",
    "venue": "H",
    "finalScore": "1-3",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-arsenal-1",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Brighton",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-arsenal-2",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Brentford",
    "venue": "H",
    "finalScore": "3-0",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-arsenal-3",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Chelsea",
    "venue": "A",
    "finalScore": "1-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-arsenal-4",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Sunderland",
    "venue": "H",
    "finalScore": "4-1",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-arsenal-5",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Spurs",
    "venue": "A",
    "finalScore": "0-1",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-bmth-1",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Newcastle",
    "venue": "A",
    "finalScore": "3-2",
    "goalsScored": 2,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-bmth-2",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Sunderland",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-bmth-3",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Fulham",
    "venue": "A",
    "finalScore": "0-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-bmth-4",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Everton",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-bmth-5",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Brentford",
    "venue": "H",
    "finalScore": "2-0",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-brentford-1",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Arsenal",
    "venue": "A",
    "finalScore": "3-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-brentford-2",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Forest",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-brentford-3",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Wolves",
    "venue": "H",
    "finalScore": "2-0",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-brentford-4",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "West Ham",
    "venue": "H",
    "finalScore": "0-2",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-brentford-5",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Everton",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-brighton-1",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Arsenal",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-brighton-2",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Villa",
    "venue": "A",
    "finalScore": "1-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-brighton-3",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "City",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-brighton-4",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Newcastle",
    "venue": "A",
    "finalScore": "0-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-brighton-5",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Liverpool",
    "venue": "A",
    "finalScore": "2-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-burnley-1",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Forest",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-burnley-2",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Palace",
    "venue": "H",
    "finalScore": "1-0",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-burnley-3",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "West Ham",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-burnley-4",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Sunderland",
    "venue": "H",
    "finalScore": "1-2",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-burnley-5",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Brighton",
    "venue": "A",
    "finalScore": "3-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-chelsea-1",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "United",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-chelsea-2",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Everton",
    "venue": "A",
    "finalScore": "0-1",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-chelsea-3",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Liverpool",
    "venue": "H",
    "finalScore": "1-2",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-chelsea-4",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Forest",
    "venue": "A",
    "finalScore": "2-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-chelsea-5",
    "formId": "form-md-3-chelsea-brighton",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Leeds",
    "venue": "H",
    "finalScore": "3-1",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-everton-1",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Forest",
    "venue": "A",
    "finalScore": "1-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-everton-2",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Palace",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-everton-3",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Leeds",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-everton-4",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "City",
    "venue": "H",
    "finalScore": "0-3",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-everton-5",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Fulham",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-forest-1",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Burnley",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-forest-2",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "West Ham",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-forest-3",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Palace",
    "venue": "H",
    "finalScore": "0-2",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-forest-4",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Chelsea",
    "venue": "H",
    "finalScore": "2-3",
    "goalsScored": 2,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-forest-5",
    "formId": "form-md-3-bournemouth-forest",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Fulham",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-fulham-1",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Wolves",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-fulham-2",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Forest",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-fulham-3",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Bournemouth",
    "venue": "H",
    "finalScore": "0-2",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-fulham-4",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Leeds",
    "venue": "A",
    "finalScore": "1-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-fulham-5",
    "formId": "form-md-3-arsenal-fulham",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Everton",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-leeds-1",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Everton",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-leeds-2",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Liverpool",
    "venue": "H",
    "finalScore": "0-3",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-leeds-3",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Chelsea",
    "venue": "A",
    "finalScore": "3-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-leeds-4",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "United",
    "venue": "A",
    "finalScore": "2-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-leeds-5",
    "formId": "form-md-3-leeds-brentford",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Fulham",
    "venue": "H",
    "finalScore": "1-2",
    "goalsScored": 1,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-liverpool-1",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Chelsea",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-liverpool-2",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Leeds",
    "venue": "A",
    "finalScore": "0-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-liverpool-3",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Spurs",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-liverpool-4",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Villa",
    "venue": "A",
    "finalScore": "1-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-liverpool-5",
    "formId": "form-md-3-everton-liverpool",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Brighton",
    "venue": "H",
    "finalScore": "2-0",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-mancity-1",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "United",
    "venue": "A",
    "finalScore": "1-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-mancity-2",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Villa",
    "venue": "H",
    "finalScore": "4-0",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-mancity-3",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Everton",
    "venue": "A",
    "finalScore": "0-3",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-mancity-4",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Sunderland",
    "venue": "H",
    "finalScore": "5-1",
    "goalsScored": 5,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-mancity-5",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Brighton",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-newcastle-1",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Forest",
    "venue": "H",
    "finalScore": "3-1",
    "goalsScored": 3,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-newcastle-2",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Barcelona",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-newcastle-3",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Brighton",
    "venue": "H",
    "finalScore": "0-3",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-newcastle-4",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Man Utd",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-newcastle-5",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Leeds",
    "venue": "A",
    "finalScore": "0-4",
    "goalsScored": 4,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-spurs-1",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Leicester",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-spurs-2",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Wolves",
    "venue": "A",
    "finalScore": "1-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-spurs-3",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Liverpool",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-spurs-4",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Arsenal",
    "venue": "H",
    "finalScore": "0-1",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-spurs-5",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "United",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-sunderland-1",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Leeds",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-sunderland-2",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "Arsenal",
    "venue": "A",
    "finalScore": "4-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-sunderland-3",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Man City",
    "venue": "A",
    "finalScore": "5-1",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-sunderland-4",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Bournemouth",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-sunderland-5",
    "formId": "form-md-3-sunderland-burnley",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Burnley",
    "venue": "A",
    "finalScore": "1-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-united-1",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "home",
    "sortOrder": 1,
    "opponent": "Chelsea",
    "venue": "A",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-united-2",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "home",
    "sortOrder": 2,
    "opponent": "City",
    "venue": "H",
    "finalScore": "1-3",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-united-3",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "home",
    "sortOrder": 3,
    "opponent": "Newcastle",
    "venue": "A",
    "finalScore": "0-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-united-4",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "home",
    "sortOrder": 4,
    "opponent": "Leeds",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-united-5",
    "formId": "form-md-3-united-newcastle",
    "teamSide": "home",
    "sortOrder": 5,
    "opponent": "Spurs",
    "venue": "H",
    "finalScore": "2-2",
    "goalsScored": 2,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-villa-1",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Palace",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-villa-2",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Brighton",
    "venue": "H",
    "finalScore": "1-3",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-villa-3",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "City",
    "venue": "A",
    "finalScore": "4-0",
    "goalsScored": 0,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-villa-4",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Liverpool",
    "venue": "H",
    "finalScore": "1-3",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-villa-5",
    "formId": "form-md-3-spurs-villa",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Everton",
    "venue": "A",
    "finalScore": "0-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-westham-1",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "away",
    "sortOrder": 1,
    "opponent": "Forest",
    "venue": "H",
    "finalScore": "2-1",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-westham-2",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "away",
    "sortOrder": 2,
    "opponent": "Palace",
    "venue": "A",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  },
  {
    "id": "formmatch-md-3-westham-3",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "away",
    "sortOrder": 3,
    "opponent": "Wolves",
    "venue": "H",
    "finalScore": "1-2",
    "goalsScored": 1,
    "outcome": "L"
  },
  {
    "id": "formmatch-md-3-westham-4",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "away",
    "sortOrder": 4,
    "opponent": "Brentford",
    "venue": "A",
    "finalScore": "0-2",
    "goalsScored": 2,
    "outcome": "W"
  },
  {
    "id": "formmatch-md-3-westham-5",
    "formId": "form-md-3-mancity-westham",
    "teamSide": "away",
    "sortOrder": 5,
    "opponent": "Burnley",
    "venue": "H",
    "finalScore": "1-1",
    "goalsScored": 1,
    "outcome": "D"
  }
] as unknown as MatchdayFormMatchRecord[];
