// Generated by scripts/premier-league/generate-club-data.mjs
// Do not edit manually unless you are intentionally overriding generated output.

export type LeagueClubRecord = {
  name: string;
  slug: string;
  badgePath: string;
  badgeSourceUrl: string;
};

export const leagueClubs: LeagueClubRecord[] = [
  {
    name: "Arsenal",
    slug: "arsenal",
    badgePath: "/assets/clubs/premier-league/arsenal.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png",
  },
  {
    name: "Aston Villa",
    slug: "aston-villa",
    badgePath: "/assets/clubs/premier-league/aston-villa.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png",
  },
  {
    name: "Bournemouth",
    slug: "bournemouth",
    badgePath: "/assets/clubs/premier-league/bournemouth.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/y08nak1534071116.png",
  },
  {
    name: "Brentford",
    slug: "brentford",
    badgePath: "/assets/clubs/premier-league/brentford.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png",
  },
  {
    name: "Brighton & Hove Albion",
    slug: "brighton-hove-albion",
    badgePath: "/assets/clubs/premier-league/brighton-hove-albion.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/ywypts1448810904.png",
  },
  {
    name: "Burnley",
    slug: "burnley",
    badgePath: "/assets/clubs/premier-league/burnley.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/ql7nl31686893820.png",
  },
  {
    name: "Chelsea",
    slug: "chelsea",
    badgePath: "/assets/clubs/premier-league/chelsea.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png",
  },
  {
    name: "Crystal Palace",
    slug: "crystal-palace",
    badgePath: "/assets/clubs/premier-league/crystal-palace.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png",
  },
  {
    name: "Everton",
    slug: "everton",
    badgePath: "/assets/clubs/premier-league/everton.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png",
  },
  {
    name: "Fulham",
    slug: "fulham",
    badgePath: "/assets/clubs/premier-league/fulham.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png",
  },
  {
    name: "Leeds United",
    slug: "leeds-united",
    badgePath: "/assets/clubs/premier-league/leeds-united.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/jcgrml1756649030.png",
  },
  {
    name: "Liverpool",
    slug: "liverpool",
    badgePath: "/assets/clubs/premier-league/liverpool.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png",
  },
  {
    name: "Manchester City",
    slug: "manchester-city",
    badgePath: "/assets/clubs/premier-league/manchester-city.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png",
  },
  {
    name: "Manchester United",
    slug: "manchester-united",
    badgePath: "/assets/clubs/premier-league/manchester-united.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
  },
  {
    name: "Newcastle United",
    slug: "newcastle-united",
    badgePath: "/assets/clubs/premier-league/newcastle-united.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png",
  },
  {
    name: "Nottingham Forest",
    slug: "nottingham-forest",
    badgePath: "/assets/clubs/premier-league/nottingham-forest.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/bk4qjs1546440351.png",
  },
  {
    name: "Sunderland",
    slug: "sunderland",
    badgePath: "/assets/clubs/premier-league/sunderland.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/tprtus1448813498.png",
  },
  {
    name: "Tottenham Hotspur",
    slug: "tottenham-hotspur",
    badgePath: "/assets/clubs/premier-league/tottenham-hotspur.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/dfyfhl1604094109.png",
  },
  {
    name: "West Ham United",
    slug: "west-ham-united",
    badgePath: "/assets/clubs/premier-league/west-ham-united.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png",
  },
  {
    name: "Wolverhampton Wanderers",
    slug: "wolverhampton-wanderers",
    badgePath: "/assets/clubs/premier-league/wolverhampton-wanderers.png",
    badgeSourceUrl: "https://r2.thesportsdb.com/images/media/team/badge/u9qr031621593327.png",
  },
];
